using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;

namespace Status.Models;

public static class SeedData
{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());

        if (context.Products.Any()) 
        {
            return;
        }

        context.Products.AddRange(
            new Product { Name = "Sneaker", Description = "Crafted from supple, full-grain white leather, these luxurious sneakers exude understated elegance. Subtle perforations detail the side panels, offering breathability. The cushioned insole and padded collar ensure exceptional comfort for all-day wear. Minimalist design is accentuated by tonal stitching and a durable rubber outsole. These pristine white sneakers effortlessly blend high-quality materials with a refined aesthetic, making them a versatile staple for any discerning wardrobe.", ImageURL = "img/sneaker.jpg"},
            new Product { Name = "Boot", Description = "Indulge in the sophistication of these luxurious black boots, meticulously crafted from premium, polished leather. Their sleek silhouette is enhanced by subtle stitching and a refined, low heel. The supple leather lining and cushioned insole provide unparalleled comfort. A durable leather outsole ensures lasting quality. These timeless black boots exude an air of refined elegance, making them a versatile and essential addition to any well-curated wardrobe, perfect for both formal occasions and elevated everyday wear.", ImageURL = "img/boot.jpg" },
            new Product { Name = "Slides", Description = "Step into plush comfort with these luxurious pink slides. Crafted from a soft, cloud-like material in a vibrant hue, they offer a delightful tactile experience. The contoured footbed provides ergonomic support for effortless wear. Their bold yet playful design makes a statement, perfect for lounging in style or adding a touch of whimsy to casual outings. These indulgent pink slides redefine relaxation with their superior comfort and eye-catching aesthetic.", ImageURL = "img/slide.jpg" },
            new Product { Name = "Running Shoe", Description = "Experience unparalleled performance in these luxurious blue running shoes. Engineered with a breathable, lightweight knit upper in a striking azure hue, they offer a secure and comfortable fit. Advanced cushioning technology provides exceptional responsiveness and support for every stride. Subtle design accents and a durable outsole complete this high-performance footwear, seamlessly blending athletic prowess with sophisticated style for the discerning runner.", ImageURL = "img/running.jpg"},
            new Product { Name = "Hiking Shoe", Description = "Crafted from premium waterproof leather, these brown hiking sneakers offer both style and practicality. The durable design features intricate stitching, a comfortable EVA footbed and midsole, and a robust rubber outsole with multi-directional lugs for superior traction. Ideal for outdoor adventures, these sneakers provide comfort, durability, and a touch of luxury.", ImageURL = "img/hiking.jpg"},
            new Product { Name = "Loafer", Description = "Crafted from supple, full-grain tan leather, this luxurious loafer exudes understated elegance. Its refined silhouette features meticulous stitching and a comfortable leather lining. The rich tan hue offers versatility, pairing effortlessly with both casual and semi-formal attire. A durable yet sleek sole ensures lasting quality and comfortable wear. This loafer is a testament to timeless style and superior craftsmanship, a sophisticated addition to any discerning wardrobe.", ImageURL = "img/loafer.jpg"},
            new Product { Name = "Espadrille", Description = "Indulge in the effortless elegance of this luxurious espadrille. Crafted from velvety soft suede in a rich navy hue, it features delicate laser-cut detailing for a touch of refinement. The natural jute sole is meticulously stitched, offering both comfort and artisanal charm. A supple leather insole ensures a luxurious feel with every step. Perfect for warm weather, this espadrille elevates casual style with its sophisticated design and premium materials.", ImageURL = "img/espadrille.jpg"},
            new Product { Name = "Kitchen Heel", Description = "Step into culinary confidence with this striking, luxurious red kitchen heel. Crafted from high-gloss patent leather, its bold silhouette commands attention. The sculpted heel offers elegant elevation while ensuring stability for the busy chef. A cushioned insole provides exceptional comfort during long hours in the kitchen. This statement piece seamlessly blends high fashion with practicality, making every culinary creation a stylish affair. It's not just a shoe; it's an expression of passionate artistry.", ImageURL = "img/kitchenheel.jpg"},
            new Product { Name = "Wedge Heel", Description = "Elevate your style with this luxurious black wedge heel. Crafted from supple black leather, its sleek silhouette exudes sophistication. The rich, dark brown wooden wedge adds a touch of earthy elegance, while the delicate gold-buckled ankle strap ensures a secure and stylish fit. Perfect for day or night, this versatile heel effortlessly combines comfort and high fashion. It's a statement piece that will turn heads wherever you go.", ImageURL = "img/wedgeheel.jpg"},
            new Product { Name = "Cowboy Boot", Description = "Crafted from rich, full-grain leather in a deep, burnished brown, this luxurious cowboy boot exudes timeless Western elegance. Intricate stitching details adorn the shaft and vamp, showcasing exceptional artistry. Subtle silver embellishments add a touch of refined flair. The classic silhouette features a comfortable stacked heel and a durable leather sole. This boot is a statement of enduring style and superior craftsmanship, perfect for those who appreciate both heritage and luxury.", ImageURL = "img/cowboyboot.jpg"},
            new Product { Name = "Moccasin", Description = "Indulge your feet in the unparalleled comfort of these luxurious moccasins. Handcrafted from the finest supple suede in a rich chestnut hue, they feature meticulous hand-stitched detailing along the vamp. A plush shearling lining envelops your feet in warmth and softness. The flexible rubber sole ensures effortless movement and lasting wear. Adorned with delicate leather ties and subtle embellishments, these moccasins redefine relaxed elegance. Experience the ultimate in comfort and understated style.", ImageURL = "img/mocassin.jpg"},
            new Product { Name = "High top Sneakers", Description = "Step into elevated streetwear with these luxurious high-top sneakers. Crafted from supple, full-grain leather in a rich caramel hue, they boast meticulous stitching and a refined silhouette. Gold-toned eyelets and subtle embossed detailing add touches of opulence. A comfortable leather lining and cushioned insole ensure all-day wearability. The durable rubber outsole provides excellent traction. These sneakers seamlessly blend sporty aesthetics with premium materials, making a sophisticated statement.", ImageURL = "img/hightop.jpg"},
            new Product { Name = "Tassel Loafer", Description = "Step out in polished style with these sophisticated patent leather tassel loafers. The high-shine black patent leather exudes a sleek and refined aesthetic. Classic tassel detailing adds a touch of traditional charm. A comfortable leather lining ensures a luxurious feel, while the durable sole provides lasting wear. Perfect for both formal occasions and adding a touch of elegance to smart-casual ensembles, these loafers are a timeless addition to any well-dressed individual's collection.", ImageURL = "img/tassel.jpg"},
            new Product { Name = "Snow Shoe", Description = "Embark on winter adventures with unparalleled style in these luxurious snowshoes. Handcrafted with rich, dark hardwood frames and intricately woven decking, they exude timeless elegance. Supple, hand-stitched leather bindings ensure a secure and comfortable fit, complemented by polished metal hardware. Designed for both performance and aesthetics, these snowshoes transform a practical necessity into a statement of refined outdoor living. Glide through pristine snowscapes with exceptional grace and sophistication.", ImageURL = "img/snow.jpg"},
            new Product { Name = "Chelsea Boot", Description = "Indulge in timeless sophistication with these luxurious black Chelsea boots. Crafted from impeccably smooth, high-quality black leather, their sleek silhouette is both elegant and versatile. Subtle elastic side panels ensure a comfortable and secure fit, while the refined leather lining adds an extra touch of luxury. A subtly stacked heel and durable leather sole complete this classic design. Perfect for elevating both smart-casual and formal ensembles, these boots are a testament to enduring style and superior craftsmanship.", ImageURL = "img/chelsea.jpg"},
            new Product { Name = "Casual Sneaker", Description = "Elevate your casual style with this luxurious take on a classic sneaker. Crafted from premium, off-white leather, it features subtle tonal stitching and refined gold-tone eyelets. The iconic star detail is subtly integrated, adding a touch of heritage. A comfortable leather lining and cushioned insole ensure all-day wearability. The slightly elevated platform sole offers a contemporary edge. These sneakers seamlessly blend iconic design with high-quality materials for a sophisticated yet relaxed look.", ImageURL = "img/casual.jpg"},
            new Product { Name = "High Heel", Description = "This elegant woman's shoe showcases a sophisticated two-tone design. Crafted with a classic pointed toe in rich black leather, it transitions to a soft, blush-toned body. The sleek, high stiletto heel adds a touch of glamour and elevates the silhouette. The refined lines and contrasting colors create a timeless and versatile style, perfect for both professional settings and special occasions. These heels are a statement of understated chic.", ImageURL = "img/highheel.jpg"},
            new Product { Name = "Knee high Heel", Description = "These luxurious knee-high stiletto heels exude sophisticated glamour. Crafted from supple, high-gloss black leather, their sleek silhouette commands attention. A delicate ankle strap, adorned with a sparkling crystal buckle, adds a touch of opulence. The slender stiletto heel and sharp, pointed toe create an elegant and elongated line. Perfect for making a statement, these heels are the epitome of refined style and confident allure.", ImageURL = "img/knee.jpg"},
            new Product { Name = "Rain Boot", Description = "Embrace wet weather in style with these luxurious rain boots. Crafted from supple, dark brown leather with a sophisticated matte finish, they exude understated elegance. The sleek, minimalist design is accented by a subtle embossed pattern, adding a touch of refinement. A sturdy rubber sole provides reliable traction, while the comfortable lining ensures all-day wearability. These rain boots seamlessly blend practicality with high fashion, making them a must-have for the discerning individual.", ImageURL = "img/rainboot.jpg"},
            new Product { Name = "Gym Shoe", Description = "Experience peak performance in these luxurious athletic gym shoes. Crafted from supple white leather, their streamlined design emphasizes both style and functionality. Strategic perforations enhance breathability, while the cushioned insole provides exceptional comfort and support. The innovative, sculpted midsole offers responsive energy return. A durable rubber outsole ensures excellent traction for any workout. These refined sneakers seamlessly blend high-performance features with a minimalist aesthetic, making them a sophisticated choice for the discerning athlete.", ImageURL = "img/gym.jpg"},
            new Product { Name = "Workwear Shoe", Description = "This durable workwear shoe is built for demanding environments. Crafted from robust, full-grain black leather, it offers excellent protection and longevity. The sturdy lace-up design ensures a secure and supportive fit. A reinforced toe provides added safety, while the cushioned insole delivers all-day comfort. The high-traction, slip-resistant outsole offers stability on various surfaces. This practical and reliable shoe is an essential for those who require dependable footwear for their work.", ImageURL = "img/workwear.jpg"},
            new Product { Name = "Basketball Shoe", Description = "This high-performance basketball shoe is engineered for agility and support on the court. Its dynamic design features a breathable knit upper in a striking blue hue, accented by vibrant orange details. Strategic overlays provide enhanced stability, while the cushioned midsole delivers responsive impact absorption. The high-top silhouette offers excellent ankle support, and the multi-directional traction pattern on the outsole ensures superior grip for quick cuts and pivots. This shoe blends cutting-edge technology with bold style to elevate your game.", ImageURL = "img/basketball.jpg"},
            new Product { Name = "Football Shoe", Description = "This luxurious American football shoe combines high performance with refined style. Crafted from supple black leather, it features a custom-designed, gridiron-inspired pattern embossed on the side. Gold accents and a gold-plated logo add a touch of opulence. The durable yet lightweight rubber sole provides optimal traction and support, while the soft, luxurious interior lining ensures ultimate comfort. This shoe is a statement of both athletic prowess and sophisticated taste.", ImageURL = "img/football.jpg"},
            new Product { Name = "Baseball Shoe", Description = "Step up to the plate in style with this luxurious baseball shoe. Crafted from rich, full-grain brown leather, it exudes classic elegance. Striking gold accents, including the sleek logo and durable metal cleats, add a touch of opulence. The cushioned interior and supportive construction ensure exceptional comfort and performance. This shoe seamlessly blends high-quality materials with a sophisticated aesthetic, making it a standout choice for the discerning player.", ImageURL = "img/baseball.jpg"},
            new Product { Name = "Soccer Shoe", Description = "This luxurious soccer cleat is crafted from supple black leather with intricate gold stitching, highlighting the brand's logo. The sole boasts a bright, iridescent finish that shifts hues in different lights. The studs are sturdy yet lightweight, strategically placed for optimal traction. It's a blend of performance and high-end design.", ImageURL = "img/soccer.jpg"}

        );  

        context.SaveChanges();

            Review SneakerReview = new Review {
            Score = 5,
            ReviewText = "Absolutely stunning! The leather is so soft, and they feel incredibly comfortable. The minimalist design is chic and goes with everything. Worth every penny for the quality and style.",
            Product = context.Products.Where(p => p.Name == "Sneaker").Single()
        };
        context.Add(SneakerReview);
        context.SaveChanges();
    }
}